apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-demo
  annotations:
    description: "This is a demo deployment for nginx"
    kubernetes.io/change-cause: "Initial deployment of nginx"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
        name: nginx-pod1
        labels:
            app: nginx-demo
    spec:
        containers:
            - name: nginx-container
              image: nginx:latest
              ports:
                  - containerPort: 80